### PR TITLE
NGImap4EnvelopeAddress decodes parameters on init

### PR DESCRIPTION
**Pull request by icandigitbaby**
This way we are able to decode email addresses with the format
=?utf-8?q?foo=5Fbar@foo=5Fbar.com?=  =>  foo_bar@foo_bar.com

### CODE REVIEW

**Comment by sixstone-qq** [comment]
:+1:

**Comment by blaxter** [comment]
:-1: First I've found that this is wrong and only working for users of the same domain, that's easy to fix but after that I've also found that if you send an email with @ in their name the email address is also broken. To sum up: fuck encodings

**Comment by blaxter** [comment]
The issue with @ on the name is separate and probably is in openchange side, no sope's fault, he's just parsing what imap told him.

**Comment by blaxter** [comment]
I've updated my branch with the changes needed to make it work for both internal and external emails. The problem was that the encoded field is the full email address in the case of external ones. In internal messages the encoded thing was only the mailbox name 511e8558e8187923f1249d5246653090bbd3dbb7

Also changed memory management of variables, there was a leak

**Comment by blaxter** [comment]
I've pushed another [branch](https://github.com/Zentyal/sope/commit/fb4721f10346df77e897f68baea50fe52dd1466f) but I don't know what is right, what is wrong or which is my name.


Actually I don't really know if this is the place to fix the string and I think that both patches are wrong and what is wrong is the data on imap because we are sending the email wrong and that's why an envelope imap response has the addresses QP encoded when they should be already [decoded](https://tools.ietf.org/html/rfc3501#section-2.3.5).

**Comment by sixstone-qq** [comment]
@blaxter then it may be better to find where we are sending incorrectly the mail... or it is better to apply this fix and go :)

**Comment by blaxter** [comment]
If I send an email using thunderbird I end up with a mail with a header `To: foo_bar@foo.com` or `To: "foo_bar@bar.com foo_bar@bar.com" <foo_bar@foo.com>`. 

If I send an email with outlook using a `to` field like `"name" <email>`, the header is ok `to: `"foo@bar@bar" <foo_bar@foo.com>` but if an email is sent with `to` field just like `email` the field ends like `to: =?utf-8?q?foo=5Fbar@yopmail.com?= <foo_bar@yopmail.com>` so the problem is that this field is being generated bad (I don't know yet where or by who is being generated). In this case we don't have the name, only email so I think is clear that is bad generated.

**Comment by blaxter** [comment]
The problem is encoding the headers, not decoding them. Closing this pr.

**Pull request closed without merging**
