### PR TITLE
Properly free socket when new connection fails

### PR DESCRIPTION
**Pull request by exekias**

### CODE REVIEW

**Comment by blaxter** [comment]
:+1:

**Comment by sixstone-qq** [comment]
:100:

**Comment by sixstone-qq** [comment]
I merged this too early as it produces compilation warnings:
```
 Compiling file NGActiveSocket.m ...
NGActiveSocket.m: In function ‘+[NGActiveSocket socketConnectedToAddress:]’:
NGActiveSocket.m:189:7: warning: multiple methods named ‘-close’ found [enabled by default]
       [sock close];
       ^
In file included from /usr/include/GNUstep/Foundation/Foundation.h:110:0,
                 from common.h:27,
                 from NGActiveSocket.m:66:
/usr/include/GNUstep/Foundation/NSStream.h:83:1: note: using ‘-(void)close’
 - (void) close;
 ^
/usr/include/GNUstep/Foundation/NSStream.h:83:1: note: also found ‘-(void)close’
In file included from ../NGStreams/NGStreams/NGStream.h:27:0,
                 from ../NGStreams/NGStreams/NGStreamExceptions.h:26,
                 from common.h:134,
                 from NGActiveSocket.m:66:
../NGStreams/NGStreams/NGStreamProtocols.h:53:1: note: also found ‘-(BOOL)close’
 - (BOOL)close;
 ^
```
Could you take a look @exekias please?

**Comment by exekias** [comment]
I saw it already, it is a legit warning isn't it? Basically close method has 2 different signatures, and it warns you it's automatically choosing one of them

**Comment by sixstone-qq** [comment]
Wouldn't it be better if we choose one?

**Comment by blaxter** [comment]
Actually the close call is not necessary because by default NGSocket has a flag `self->flags.closeOnFree = YES;` which will force to call `close` method on release.

The warning can also be avoided using `NGActiveSocket *` instead of `id` or using release method. I don't understand why `id` is used there (also I don't understand all the id<xxx> usages in the code)

**Comment by blaxter** [comment]
Also I don't understand why `[self release]` is called in a class method.

**Comment by blaxter** [comment]
And the `volatile` keyword is also redundant imho

**Pull request merged**
